### ISSUE TITLE
MLST step failed

### ISSUE THREAD

**Issue by Moana63** [fmalmeida/bacannot#92] opened 2023-04-21 12:48 UTC
Hi there,

I am encountering an issue when running the pipeline on a server (centos linux 7), everything runs fine until the MLST steps. It looks like the pipeline is trying to add bases to the tool's directory, but singularity doesn't let it, which is - to my understanding - the expected behavior. I use a nextflow-22.10.4 environment.
Here is the error :

Command executed:

  # update tool database
  mlst_dir=$(which mlst | sed 's/bin\/mlst//g')
  cp bacannot_dbs/mlst_db/* -r ${mlst_dir}/db/pubmlst/
  ( cd $mlst_dir/scripts && ./mlst-make_blast_db )
  
  # Save mlst tool version
  mlst --version > mlst_version.txt ;
  
  # run mlst
  mlst \
      --quiet \
      --novel ptg00000294c_novel_alleles.fasta \
      ptg00000294c.fna > ptg00000294c_mlst_analysis.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  cp: cannot create regular file '/opt/conda//db/pubmlst/dbases.xml': Read-only file system

Thank you for your help,
Regards,
Moana

**Comment by fmalmeida** [comment] 2023-04-21 13:37
Hi @Moana63 ,
Thanks for reporting this issue.
Before I start tackling this problem, since I am in the middle of trying to finalise a new release and, there I had some work in this module …

could you try running the dev branch? Just to check if the error persists or not sonI can try to speed up the next release.

Thanks for using the tool!

**Comment by Moana63** [comment] 2023-04-24 12:23
Hi,
Thank you for your quick answer ! I tried running it with the dev branch and the MLST runs without issue. 
However I got the following error regarding the CREATE_SQL step (still on dev branch:

Error executing process > 'BACANNOT:CREATE_SQL (ptg000001c)'

Caused by:
  Process `BACANNOT:CREATE_SQL (ptg000001c)` terminated with an error exit status (1)

Command executed:

  if [ -s digIS.fa ] ;
  then
  
    # concatenate files
    cat ptg000001c.gff digIS.gff | bedtools sort > input.gff
    cat ptg000001c.ffn digIS.fa  > input.fa
    cat ptg000001c.faa digIS.faa > input.faa
  
    # Create SQL db
    gff2sql.R -i input.gff -o ptg000001c.sqlite -n input.fa -a input.faa -f ptg000001c.fna &> gff2sql.log;
  
  else
  
    # Create SQL db
    gff2sql.R -i ptg000001c.gff -o ptg000001c.sqlite -n ptg000001c.ffn -a ptg000001c.faa -f ptg000001c.fna &> gff2sql.log;
  
  fi
  
  # Save results with better name
  mv /work/ptg000001c.sqlite . ;
  
  # Save parser
  cp /work/bscripts/run_server.sh . ;

Command exit status:
  1

Command output:
  (empty)

**Comment by fmalmeida** [comment] 2023-04-24 12:41
Hi @Moana63 ,

Thanks for the feedback.
First of all, good to hear the the MLST-singularity problem is already solved in the next version.
For the new error, I have some comments and suggestions so I can try to figure what it is, if it is specifically related to singularity or to the dataset.

1. Could you send me the files that are availalble in this work directory?
    + Specially the nextflow files and the `gff2sql.log` file.
2. Could you try running with a public dataset? Maybe with the example use case shown in the manual or another reference genome and see if it works? Just to check if it is singularity or dataset related.

In the meantime, I will also find a way of launching and debugging a singularity execution of dev branch with a dataset of mine to see if I can replicate it.

Kind regards,
Felipe.

**Comment by fmalmeida** [comment] 2023-04-27 06:14
Hello,
Getting back on this. I would really need to see the logs to understand the error. When I executed the test dataset:

`nextflow run fmalmeida/bacannot -r dev -profile test,singularity` it worked fine.

**Comment by fmalmeida** [comment] 2023-05-04 09:10
I just pushed a small change to the singularity config in dev branch that may (or may not) help with this issue. Could you give it a try later?
:)

**Comment by fmalmeida** [comment] 2023-05-08 14:31
I could reproduce the error, am now working on a fix.

**Comment by fmalmeida** [comment] 2023-05-08 17:28
Hi @Moana63 ,
I could reproduce and now fixed the error. It should be working now. If you can delete your previously downloaded singularity images and let the pipeline download them again (new versions) it should work.

Remember to use `-r dev -latest` to make sure to use the latest version of the dev branch.

**Comment by fmalmeida** [comment] 2024-03-11 17:46
Did not get back from user and could not reproduce.
If still a thing we can re-open the issue to tackle over the new release.

**Closed by fmalmeida** 2024-03-11 17:46 UTC
