### ISSUE TITLE
Issue with Antismash

### ISSUE THREAD

**Issue by fetyj** [fmalmeida/bacannot#71] opened 2022-11-03 13:35 UTC
Hi Felipe,
I hope you are doing well. I'm annotatin some genomes with bacannot but the process is always stuck on the Antismash analysis.
Could you help resolve this one? 
Thanks,
Fety
```N E X T F L O W  ~  version 22.04.4
Launching `https://github.com/fmalmeida/bacannot` [pedantic_mandelbrot] DSL2 - revision: 8841acfcdb [master]


------------------------------------------------------
  fmalmeida/bacannot v3.1.5
------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : pedantic_mandelbrot
  containerEngine: docker
  launchDir      : /choppy
  workDir        : /choppy/work
  projectDir     : /home/fiestaj/.nextflow/assets/fmalmeida/bacannot
  userName       : fiestaj
  profile        : docker
  configFiles    : /home/fiestaj/.nextflow/assets/fmalmeida/bacannot/nextflow.config

Input/output options
  input          : /choppy/yaml_files/Lb_6369.yaml
  output         : /choppy/Bacteria_assembly/Bacannot_bioprox_strain/Lb_6369
  bacannot_db    : bacannot_dbs
  bakta_db       : null

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use fmalmeida/bacannot for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.3627669

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/fmalmeida/bacannot/blob/master/CITATIONS.md
executor >  local (20)
[-        ] process > BACANNOT:UNICYCLER                -
[-        ] process > BACANNOT:FLYE                     -
[67/bb035a] process > BACANNOT:PROKKA (Lb_6369)         [100%] 1 of 1 ✔
[90/922b0b] process > BACANNOT:MLST (Lb_6369)           [100%] 1 of 1 ✔
[d4/900757] process > BACANNOT:BARRNAP (Lb_6369)        [100%] 1 of 1 ✔
[8b/bff416] process > BACANNOT:COMPUTE_GC (Lb_6369)     [100%] 1 of 1 ✔
[-        ] process > BACANNOT:KOFAMSCAN                [  0%] 0 of 1
[-        ] process > BACANNOT:KEGG_DECODER             -
[e5/9d568e] process > BACANNOT:PLASMIDFINDER (Lb_6369)  [100%] 1 of 1 ✔
[41/b47cd3] process > BACANNOT:PLATON (Lb_6369)         [  0%] 0 of 1
[22/22364b] process > BACANNOT:ISLANDPATH (Lb_6369)     [100%] 1 of 1 ✔
[15/3260b8] process > BACANNOT:VFDB (Lb_6369)           [100%] 1 of 1 ✔
[a6/3c0d2e] process > BACANNOT:VICTORS (Lb_6369)        [100%] 1 of 1 ✔
[bb/fdc9f0] process > BACANNOT:PHAST (Lb_6369)          [100%] 1 of 1 ✔
[fd/6c5b0c] process > BACANNOT:PHIGARO (Lb_6369)        [  0%] 0 of 1
[c2/2fb553] process > BACANNOT:PHISPY (Lb_6369)         [100%] 1 of 1 ✔
[8a/c21660] process > BACANNOT:ICEBERG (Lb_6369)        [100%] 1 of 1 ✔
[f2/bc5275] process > BACANNOT:AMRFINDER (Lb_6369)      [  0%] 0 of 1
[c2/328953] process > BACANNOT:CARD_RGI (Lb_6369)       [  0%] 0 of 1
[93/08498e] process > BACANNOT:ARGMINER (Lb_6369)       [100%] 1 of 1 ✔
[-        ] process > BACANNOT:RESFINDER                -
[-        ] process > BACANNOT:CALL_METHYLATION         -
[4c/f28ecf] process > BACANNOT:REFSEQ_MASHER (Lb_6369)  [100%] 1 of 1 ✔
[a0/cf2ecd] process > BACANNOT:DIGIS (Lb_6369)          [100%] 1 of 1 ✔
[98/6c52d7] process > BACANNOT:ANTISMASH (Lb_6369)      [  0%] 0 of 1
[72/de0f75] process > BACANNOT:SEQUENCESERVER (Lb_6369) [100%] 1 of 1 ✔
[-        ] process > BACANNOT:MERGE_ANNOTATIONS        -
[-        ] process > BACANNOT:DRAW_GIS                 -
[-        ] process > BACANNOT:GFF2GBK                  -
[-        ] process > BACANNOT:CREATE_SQL               -
[-        ] process > BACANNOT:JBROWSE                  -
[-        ] process > BACANNOT:REPORT                   -
Error executing process > 'BACANNOT:ANTISMASH (Lb_6369)'

Caused by:
  Process `BACANNOT:ANTISMASH (Lb_6369)` terminated with an error exit status (2)

Command executed:

  # Activate env
  export PATH=/opt/conda/envs/antismash/bin:$PATH
  
  # Get tool version
  antismash --version > antismash_version.txt ;
  
  # Run tool
  antismash \
    --output-dir antiSMASH \
    --genefinding-tool none \
    -c 4 \
    --databases bacannot_dbs/antismash_db \
    Lb_6369.gbk ;
  
  # enter results dir
  cd antiSMASH ;
  
  # produce gff from main results
  seqret \
    -sequence Lb_6369.gbk \
    -feature \
    -fformat genbank \
    -fopenfile Lb_6369.gbk \
    -osformat gff \
    -osname_outseq Lb_6369 \
    -auto ;
  
  # get the locus tags annotated as list
  grep \
    "locus_tag" \
    *region*gbk | \
    cut \
    -f 2 \
    -d "=" | \
    tr -d '"' | \
    sort -u > gene_ids.lst ;
  
  # subset regions GFF from main GFF for JBrowse
  grep \
    -w \
    -f gene_ids.lst \
    Lb_6369.gff > regions.gff ;

Command exit status:
  2

Command output:
  (empty)

Command error:
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'
  Warning: Lb_6369_6: Bad value 'COORDINATES:profile:Aragorn:001002' for tag '/inference'
  Warning: bad /inference value 'COORDINATES:profile:Aragorn:001002' type: 'COORDINATES'

Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'BACANNOT:ANTISMASH (Lb_6369)'

Work dir:
  /choppy/work/98/6c52d7b4f08f94958e6bdf25be2560

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by fmalmeida** [comment] 2022-11-03 13:58
Hi @fetyj,

Since I have done no changes in the pipeline, I assume there is a problem with the generated `.gbk` file for that sample. So I can try to replicate and troubleshoot it, I ask if it is possible:

* That you send the results of a `tree -L 2` command in the workdir
* It seems that the problem is the 6th contig: `Lb_6369_6`. Is it possible that you send me either the contig so I can try to execute the entire pipeline with contig 6, or the subsetted `.gbk` file with these entries that cause the error?
* Can you send me a snapshot of the `.gbk` file near where these failling entries are so I can how it looks like?

Thanks for using the pipeline. Let's fix that so you can get your analyses going :)

**Comment by fetyj** [comment] 2022-11-03 14:03
Just emailed the fasta file :)

**Comment by fmalmeida** [comment] 2022-11-03 14:14
Okidokie,
I'll start the pipeline with it to try to troubleshoot.

**Comment by fmalmeida** [comment] 2022-11-03 19:02
Hi @fetjy,

I've been able to replicate your error using your input. Also, when using a different genome, everything ran ok.

So, I confirmed that there is no 'error' in the module, but, something interesting may be happening from your input point of view.

I will try in the following days to find a way so that the module can be "smart" enough to understand the normal scenario where things go ok, but to also understand and accept the scenario of your data, for example.

😄

**Comment by fmalmeida** [comment] 2022-11-03 19:37
@fetyj ,

Can you try running it again using the [fety-fix](https://github.com/fmalmeida/bacannot/tree/fety-fix) branch?

You can add `-r fety-fix` to your command line :)

If all goes good, I can push a fix to `master`.

**Comment by fetyj** [comment] 2022-11-04 08:00
Hi @fmalmeida ,
Adding `-r fety-fix` enable the analysis to finish but without the Antismash results. I have some genomes to work with, I will try the 2 commands to see if it's all of my genomes or just a few one, the outcome may help in understanding what is going on.
Thanks :)

**Comment by fmalmeida** [comment] 2022-11-04 08:06
Hi @fetyj,

Using the genome you provided, the expected wast that. I ran antismash and nothing was annotated using it. And that was what was causing the pipeline to break, because the pipeline was always expecting something, but, with this genome, the results from the tool were empty.

**Comment by fetyj** [comment] 2022-11-04 08:59
@fmalmeida ,
I see, thanks for the clarification.
:-)

**Comment by fmalmeida** [comment] 2022-11-04 12:40
I am reopening this one because the solution for it is still not merged in master branch.
Once it is merged and available in master with a new tag, I will close it again :)

Happy to see that it worked.

**Comment by fmalmeida** [comment] 2022-11-07 09:01
done

**Closed by fmalmeida** 2022-11-07 09:01 UTC
Labels: bug, enhancement
